name: 'GitHub Users'
description: 'GitHub Action that creates list of enterprise users or allows automatic invitation of users'
author: darko.krizic@prodyna.com
inputs:
  action:
    description: 'The action to perform, currently supported: userlist'
    required: true
  enterprise:
    description: 'The GitHub Enterprise to query for repositories'
    required: true
  github-token:
    description: 'The GitHub Token to use for authentication'
    required: true
  template-files:
    description: 'The template file to use for rendering the result'
    required: false
    default: '/template/markdown/members.tpl,/template/json/members.tpl'
  output-files:
    description: 'The output files to write the result to'
    required: false
    default: 'MEMBERS.md,members.json'
  verbose:
    description: 'The verbosity level'
    required: false
    default: 1
  own-domains:
    description: 'Own domains to filter users by email domain'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'docker://ghcr.io/prodyna/github-users:v2.0'
  env:
    ACTION: ${{ inputs.action }}
    ENTERPRISE: ${{ inputs.enterprise }}
    GITHUB_TOKEN: ${{ inputs.github-token }}
    TEMPLATE_FILES: ${{ inputs.template-files }}
    OUTPUT_FILES: ${{ inputs.markdown-files }}
    VERBOSE: ${{ inputs.verbose }}
    OWN_DOMAINS: ${{ inputs.own-domains }}
